version: '2'

services:

  blockchain-middleware:
    container_name: blockchain
    image: blockhaineveris/blockchain-middleware:master
    ports:
      - "8081:8081"
    volumes:
      - /tmp/blockchain-middleware:/tmp
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - blockchain

  blockchain-demo:
   container_name: blockchain-demo
   image: blockhaineveris/blockchain-middleware:develop
   ports:
     - "8088:8081"
   volumes:
     - /tmp/blockchain-demo:/tmp
   environment:
     JAVA_OPTS: "-Xmx1024m -Xms1024m"
   networks:
     - blockchain

networks:
  blockchain:
    driver: bridge