version: '2'

services:

  blockchain-middleware:
    container_name: blockchain-middleware
    image: blockhaineveris/blockchain-middleware:develop
    ports:
      - "8081:8080"
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - blockchain