version: '2'

services:

  blockchain-middleware:
    container_name: blockchain-middleware
    image: blockhaineveris/blockchain-middleware:develop
    ports:
      - "8081:8080"
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - blockchain

  blockchain-front:
    container_name: blockchain-front
    image: blockhaineveris/blockchain-front:3.1
    volumes:
      - ./config.ts:/blockchain-everis/src/config/config.ts
    ports:
      - "9999:9999"

networks:
  blockchain:
    driver: bridge